module.exports = {
  colors: {
    bgcolor: "white",
    colortheme: "#08c47f",
    text1: "#08c47f",
    text2: "grey",
    text3: "black",
    textgreen: "green",
    primaryColor: "white",
    themecol: "#129bad",
    
  },
  titles: {
    title1: 30,
    btntxt: 20,
  },
  btn1: {
    width: "80%",
    height: 50,
    backgroundColor: "red",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    color: "white",
    marginBottom: 10,
  },
  hr80: {
    width: "80%",
    borderBottomColor: "#E0E0E0",
    borderBottomWidth: 1,
    marginVertical: 20,
  },
  head1: {
    marginTop: "5%",
    marginBottom: "5%",
    fontSize: 30,
    color: "#08c47f",
    textAlign: "center",
    fontWeight: "500",
  },
  head2: {
    fontSize: 20,
    color: "black",
    textAlign: "center",
    
  },
  formgroup: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    marginVertical: 5,
    
  },
  label: {
    fontSize: 14,
    // color: '#F50057',
    marginLeft: 10,
    marginBottom: 3,
    color: "#08c47f",
    fontWeight: "bold",
  },
  input: {
    //backgroundColor: "#FFB0CC",
    // borderRadius: 20,
    borderWidth: 2,
    flexDirection: "row",
    marginVertical: 5,
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 5,
    paddingVertical: 8,
    fontSize: 10,
    paddingLeft: 10,
    marginBottom: 10,
    alignItems: "center",
    borderColor: "#08c47f",
  },
  textinput: {
    fontSize: 15,
    marginLeft: 10,
    width: "80%",
  },
  link: {
    textAlign: "left",
    color: "#F50057",
    fontSize: 15,
  },
  link2: {
    flexDirection: "row",
    color: "black",
    fontSize: 15,
    fontWeight: 500,
    textAlign: "center",
    marginVertical: 2,
  },
  input1: {
    backgroundColor: "#08c47f",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    height: 100,
    textAlignVertical: "top",
  },
  errormessage: {
    textAlign: "center",
    color: "red",
    fontWeight: "bold",
    fontSize: 18,
  },
  bwmessage: {
    color: "white",
    backgroundColor: "black",
    fontSize: 15,
    textAlign: "center",
    padding: 5,
    borderRadius: 5,
  },
};
